import haspmota
import json
import string
var f=open('pages.jsonl','w')
f.write('{"page":1}\n{"id":0,"bg_color":"#0000A0","bg_grad_color":"#000000","bg_grad_dir":1}\n{"id":10,"obj":"obj","x":0,"y":0,"w":240,"h":26,"bg_color":"#D00000","bg_opa":255,"radius":0,"border_width":0}\n{"id":12,"obj":"label","x":3,"y":4,"w":85,"h":18,"text":"IP","text_color":"#FFFFFF","text_font":"montserrat-14","align":0}\n{"id":13,"obj":"label","x":92,"y":4,"w":60,"h":18,"text":"SSID","text_color":"#FFFFFF","text_font":"montserrat-14","align":0}\n{"id":14,"obj":"label","x":155,"y":4,"w":65,"h":18,"text":"00:00:00","text_color":"#FFFFFF","text_font":"montserrat-14","align":0}\n{"id":15,"obj":"lv_wifi_arcs","x":215,"y":0,"w":25,"h":26,"bg_color":"#D00000","line_color":"#FFFFFF"}\n{"id":30,"obj":"label","x":5,"y":29,"w":230,"h":14,"text":"","text_color":"#FFFF00","text_font":"montserrat-14","align":0}\n{"id":31,"obj":"label","x":5,"y":44,"w":230,"h":14,"text":"","text_color":"#FFFF00","text_font":"montserrat-14","align":0}\n{"id":32,"obj":"label","x":5,"y":59,"w":230,"h":14,"text":"","text_color":"#FFFF00","text_font":"montserrat-14","align":0}\n{"id":20,"obj":"label","x":5,"y":76,"w":110,"h":14,"text":"","text_color":"#FFFFFF","text_font":"montserrat-14","align":0}\n{"id":21,"obj":"label","x":125,"y":76,"w":110,"h":14,"text":"","text_color":"#FFFFFF","text_font":"montserrat-14","align":0}\n{"id":22,"obj":"label","x":5,"y":91,"w":110,"h":14,"text":"","text_color":"#FFFFFF","text_font":"montserrat-14","align":0}\n{"id":23,"obj":"label","x":125,"y":91,"w":110,"h":14,"text":"","text_color":"#FFFFFF","text_font":"montserrat-14","align":0}\n{"id":24,"obj":"label","x":5,"y":106,"w":110,"h":14,"text":"","text_color":"#FFFFFF","text_font":"montserrat-14","align":0}\n{"id":25,"obj":"label","x":125,"y":106,"w":110,"h":14,"text":"","text_color":"#FFFFFF","text_font":"montserrat-14","align":0}\n{"id":26,"obj":"label","x":5,"y":121,"w":110,"h":14,"text":"","text_color":"#FFFFFF","text_font":"montserrat-14","align":0}\n{"id":27,"obj":"label","x":125,"y":121,"w":110,"h":14,"text":"","text_color":"#FFFFFF","text_font":"montserrat-14","align":0}\n{"id":28,"obj":"label","x":5,"y":136,"w":110,"h":14,"text":"","text_color":"#FFFFFF","text_font":"montserrat-14","align":0}\n{"id":29,"obj":"label","x":125,"y":136,"w":110,"h":14,"text":"","text_color":"#FFFFFF","text_font":"montserrat-14","align":0}\n')
f.close()
haspmota.start()
def pv(t,k)var s=string.format("%s",t);var ki=string.find(s,k);if ki==-1 return"Wait..."end;var ci=string.find(s,":",ki);if ci==-1 return"?"end;var sq=-1;var qc="";var i=ci+1;var mx=size(s);while i<mx;var c=s[i];if c=='"'||c=="'";sq=i;qc=c;break end;i+=1 end;if sq==-1 return"?"end;var eq=string.find(s,qc,sq+1);if eq==-1 return"?"end;var r="";for j:sq+1..eq-1;r+=s[j]end;return r end
class SD:Driver
def es()var rj=tasmota.read_sensors();if rj==nil return end;var m=json.load(rj);if m==nil return end;if global.p1b12!=nil;var ri=tasmota.cmd("Status 5");var ip=pv(ri,"IPAddress");global.p1b12.text=ip end;if global.p1b13!=nil;var rw=tasmota.cmd("Status 11");var ss=pv(rw,"SSId");global.p1b13.text=ss end;if global.p1b14!=nil;global.p1b14.text=tasmota.strftime("%H:%M:%S",tasmota.rtc())end;var bc=0;var bl=[global.p1b30,global.p1b31,global.p1b32];for i:0..3;var k=i==0?"BME280":string.format("BME280-%d",i);if m.contains(k)&&bc<3;var s=m[k];var t=s.find('Temperature',0.0);var h=s.find('Humidity',0.0);if bl[bc]!=nil;bl[bc].text=string.format("%s %.1f°C %.0f%%",k,t,h);bc+=1 end end end;while bc<3;if bl[bc]!=nil;bl[bc].text=""end;bc+=1 end;var dl=[global.p1b20,global.p1b21,global.p1b22,global.p1b23,global.p1b24,global.p1b25,global.p1b26,global.p1b27,global.p1b28,global.p1b29];var dc=0;for i:1..10;var k=string.format('DS18B20-%d',i);if m.contains(k)&&dc<10;var s=m[k];var id=s['Id'];var t=s['Temperature'];var si=id[8..11];if dl[dc]!=nil;dl[dc].text=string.format("..%s %.1f°C",si,t)end;dc+=1 end end;while dc<10;if dl[dc]!=nil;dl[dc].text=""end;dc+=1 end end
end
global.d=SD()
tasmota.add_driver(global.d)
tasmota.add_cron("*/1 * * * * *",/->global.d.es(),"su")
